package:
  name: tetmesh
  version: 0.0

source:
  git_url: https://github.com/siboles/tetmesh.git
  git_rev: 0.0

build:
  number: 0
  features:
    - vc9 [win and py27]

requirements:
  build:
    - python
    - setuptools
    - trimesh
    - cgal 4.8*
    - libgcc 5.2*
    - tbb 2017*
    - cmake [not osx and not win]
    - cmake-mac [osx or win]
  run:
    - python
    - cgal 4.8*
    - trimesh
    - tbb 2017*
test:
  imports:
    - tetmesh

about:
  home: https://github.com/siboles/tetmesh
  summary: "A small module for building 3-D tetrahedral meshes from polygonal surfaces."
  license: GPLv3
