package:
  name: tetmesh
  version: 0.0

source:
  git_url: https://github.com/siboles/tetmesh.git
  git_rev: 0.0

build:
  number: 0
  features:
    - vc9 [win and py27]
    - vc14 [win and py>=35]

requirements:
  build:
    - python
    - setuptools
    - vc 9 [win and py27]
    - vc 14 [win and py>=35]	
    - trimesh
    - cgal 4.10*
    - libgcc 5.2* [not osx and not win]
    - boost
    - tbb 2017*
    - cmake
  run:
    - python
    - vc 9 [win and py27]
    - vc 14 [win and py>=35]	
    - cgal 4.10*
    - trimesh
    - tbb 2017*
test:
  imports:
    - tetmesh

about:
  home: https://github.com/siboles/tetmesh
  summary: "A small module for building 3-D tetrahedral meshes from polygonal surfaces."
  license: GPL
